import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, TextInput, ActivityIndicator, Alert } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { BlurView } from 'expo-blur';
import { router } from 'expo-router';
import { useAuth } from '../context/AuthContext';
import { auth, db } from '../lib/firebase';
import { multiFactor, TotpMultiFactorGenerator, TotpSecret } from 'firebase/auth';
import { doc, updateDoc } from 'firebase/firestore';
import { ShieldAlert, Copy, CheckCircle } from 'lucide-react-native';

export default function TwoFactorSetup() {
  const { user, profile } = useAuth();
  const [totpSecret, setTotpSecret] = useState<TotpSecret | null>(null);
  const [verificationCode, setVerificationCode] = useState('');
  const [isVerifying, setIsVerifying] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!user) return;
    
    // Generate TOTP Secret
    const generateSecret = async () => {
      try {
        const multiFactorSession = await multiFactor(user).getSession();
        const secret = await TotpMultiFactorGenerator.generateSecret(multiFactorSession);
        setTotpSecret(secret);
      } catch (err: any) {
        console.error("Error generating TOTP secret:", err);
        setError("Could not generate 2FA secret. Ensure Identity Platform is enabled in Firebase.");
      }
    };
    
    generateSecret();
  }, [user]);

  const copyToClipboard = () => {
    if (totpSecret) {
      // In a real app, use Clipboard.setString(totpSecret.secretKey)
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleVerify = async () => {
    if (!user || !totpSecret || verificationCode.length !== 6) return;
    
    setIsVerifying(true);
    setError('');
    
    try {
      // Create a multi-factor assertion
      const assertion = TotpMultiFactorGenerator.assertionForEnrollment(totpSecret, verificationCode);
      
      // Enroll the user
      await multiFactor(user).enroll(assertion, 'Google Authenticator');
      
      // Update Firestore profile
      if (db) {
        await updateDoc(doc(db, 'users', user.uid), {
          mfaEnabled: true
        });
      }
      
      Alert.alert("Success", "2FA has been successfully enabled!");
      router.replace('/');
      
    } catch (err: any) {
      console.error(err);
      setError("Invalid code. Please try again.");
    } finally {
      setIsVerifying(false);
    }
  };

  return (
    <View style={styles.container}>
      <LinearGradient
        colors={['#0f172a', '#1e1b4b', '#064e3b']}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
        style={StyleSheet.absoluteFillObject}
      />
      
      <View style={styles.content}>
        <BlurView intensity={60} tint="dark" style={styles.card}>
          <View style={styles.iconContainer}>
            <ShieldAlert color="#10B981" size={48} />
          </View>
          
          <Text style={styles.title}>Secure Your Pro Account</Text>
          <Text style={styles.subtitle}>
            As a Pro Creator, mandatory Two-Factor Authentication (2FA) is required. Please set up Google Authenticator to continue.
          </Text>

          {error ? <Text style={styles.errorText}>{error}</Text> : null}

          <View style={styles.stepContainer}>
            <Text style={styles.stepTitle}>1. Copy Secret Key</Text>
            <Text style={styles.stepDesc}>Enter this key manually into Google Authenticator or Authy.</Text>
            
            <TouchableOpacity style={styles.secretBox} onPress={copyToClipboard}>
              <Text style={styles.secretText}>
                {totpSecret ? totpSecret.secretKey : 'Generating...'}
              </Text>
              {copied ? <CheckCircle color="#10B981" size={20} /> : <Copy color="#8A8F98" size={20} />}
            </TouchableOpacity>
          </View>

          <View style={styles.stepContainer}>
            <Text style={styles.stepTitle}>2. Enter 6-Digit Code</Text>
            <Text style={styles.stepDesc}>Enter the code generated by your app to verify.</Text>
            
            <TextInput
              style={styles.input}
              placeholder="000000"
              placeholderTextColor="#475569"
              keyboardType="number-pad"
              maxLength={6}
              value={verificationCode}
              onChangeText={setVerificationCode}
            />
          </View>

          <TouchableOpacity 
            style={[styles.primaryButton, verificationCode.length !== 6 && styles.buttonDisabled]}
            onPress={handleVerify}
            disabled={isVerifying || verificationCode.length !== 6}
          >
            {isVerifying ? (
              <ActivityIndicator color="#FFFFFF" />
            ) : (
              <Text style={styles.primaryButtonText}>Verify & Enable 2FA</Text>
            )}
          </TouchableOpacity>
        </BlurView>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0B0D10',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  card: {
    width: '100%',
    maxWidth: 500,
    padding: 40,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
    overflow: 'hidden',
    alignItems: 'center',
  },
  iconContainer: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  title: {
    fontSize: 32,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 12,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: '#8A8F98',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 24,
  },
  stepContainer: {
    width: '100%',
    marginBottom: 24,
  },
  stepTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  stepDesc: {
    color: '#8A8F98',
    fontSize: 14,
    marginBottom: 12,
  },
  secretBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  secretText: {
    color: '#60A5FA',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 2,
  },
  input: {
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 12,
    padding: 16,
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 8,
    textAlign: 'center',
  },
  errorText: {
    color: '#EF4444',
    marginBottom: 16,
    textAlign: 'center',
  },
  primaryButton: {
    width: '100%',
    backgroundColor: '#10B981',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 12,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
});
